### ISSUE TITLE
Use User Entered Humans

### ISSUE THREAD

**Issue by jzongker** [KZongker/dragons#11]
On both your human list and the battle calculator, include the user created humans from #10 

Load the array from stats.js, and also load the array from localStorage if it exists.  Merge the two together.

**Comment by KZongker** [comment]
Closed with https://github.com/KZongker/dragons/commit/73959627a383dc0897f7e0632817cad9aef2837c

**Comment by KZongker** [comment]
Just kidding, closed with: https://github.com/KZongker/dragons/commit/c0b9ed4efcf471faf64c905bc1addf8bee5be294
