### ISSUE TITLE
Handle keyboard input

### ISSUE THREAD

**Issue by jzongker** [KZongker/dragons#19]
Add a key down listener.  Handle wasd or arrows and call empty lip, down, left, right functions that console log

**Comment by jzongker** [comment]
You should create a new game.js file for this game code

**Comment by KZongker** [comment]
Closed with: https://github.com/KZongker/dragons/commit/50f90005d1204621d3277e7df493c5ae56ee43b6
Movement includes WASD and Arrowkeys. Console.log available but commented out.
