### ISSUE TITLE
Handle dragon movement

### ISSUE THREAD

**Issue by jzongker** [KZongker/dragons#20]
There's gonna be math here..

My suggestion is to have two variables:

- Horizontal which will store -1 left, 0, none, or 1 right
- Vertical which will store a value of 1 when the user clicks up, and then decreases by 0.1 every 100ms until it reaches -1, due to gravity

Set a 100ms timer that will move the dragon based on the horizontal and vertical settings and recalculate the new vertical

I would suggest moving him a percentage of the container on each timer tick.  So after 100ms he moves right 1%

**Comment by KZongker** [comment]
Closed with: https://github.com/KZongker/dragons/commit/10d00b4986dc37610ab60cd08a696cbd938e5481
Will likely update for arrow keys too, hence key input issue staying open.
