### ISSUE TITLE
Move human stats to array

### ISSUE THREAD

**Issue by jzongker** [KZongker/dragons#5]
Create a new stats.js file that includes an array of humans with their name, dragon, age, and stats.

Bonus if you also include an array of dragons.

**Comment by jzongker** [comment]
I guess you'll also need fields for photoUrl and the card color

**Comment by KZongker** [comment]
Working on with this: https://github.com/KZongker/dragons/commit/ae0b0631deaf2539f707c3106baa7b7a87b3da28
Not sure if correct, would like to discuss after dinner if this is seen before then

**Comment by KZongker** [comment]
Closed with: https://github.com/KZongker/dragons/commit/f86d485b0e9226083ff2395983889c4187f7ed3c
