### ISSUE TITLE
Go full width with site

### ISSUE THREAD

**Issue by jzongker** [KZongker/dragons#7]
We're going to need more screen space to build a game.  Update the site layout to fill the full width of the browser and remove the scrolling div.  You can use a minHeight instead of height on the main content area to make sure it still looks ok with little content but allow it to grow indefinitely when there's a lot of content.

**Comment by KZongker** [comment]
closed with: https://github.com/KZongker/dragons/commit/83728403de4626165370cd40d3564eb389c18a45
