### ISSUE TITLE
Create a graphical game

### ISSUE THREAD

**Issue by jzongker** [KZongker/dragons#9]
Create a game where you can fly a dragon around the screen and pick up sheep.

You can use a dragon image with absolute position to move it around the screen.  And maybe invert the image when the dragon needs to fly left.

Either add buttons for up, down, left, right or listen for keyboard input.

**Comment by KZongker** [comment]
Closed with: https://github.com/KZongker/dragons/commit/93dd6be9e89d09a4b2941ae0ba7f0eb0b557d353
